In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

training_images = pd.read_csv('../input/sign-language-mnist/sign_mnist_train/sign_mnist_train.csv')
testing_images = pd.read_csv('../input/sign-language-mnist/sign_mnist_test/sign_mnist_test.csv')
print(training_images.head())

/kaggle/input/sign-language-mnist/american_sign_language.PNG
/kaggle/input/sign-language-mnist/amer_sign3.png
/kaggle/input/sign-language-mnist/sign_mnist_train.csv
/kaggle/input/sign-language-mnist/sign_mnist_test.csv
/kaggle/input/sign-language-mnist/amer_sign2.png
/kaggle/input/sign-language-mnist/sign_mnist_test/sign_mnist_test.csv
/kaggle/input/sign-language-mnist/sign_mnist_train/sign_mnist_train.csv
   label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      3     107     118     127     134     139     143     146     150   
1      6     155     157     156     156     156     157     156     158   
2      2     187     188     188     187     187     186     187     188   
3      2     211     211     212     212     211     210     211     210   
4     13     164     167     170     172     176     179     180     184   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     153  ...       207       207       207       207 

In [2]:
print(testing_images.head())

   label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      6     149     149     150     150     150     151     151     150   
1      5     126     128     131     132     133     134     135     135   
2     10      85      88      92      96     105     123     135     143   
3      0     203     205     207     206     207     209     210     209   
4      3     188     191     193     195     199     201     202     203   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     151  ...       138       148       127        89        82        96   
1     136  ...        47       104       194       183       186       184   
2     147  ...        68       166       242       227       230       227   
3     210  ...       154       248       247       248       253       236   
4     203  ...        26        40        64        48        29        46   

   pixel781  pixel782  pixel783  pixel784  
0       106       112       12

In [3]:
training_images_x = training_images.drop('label', axis=1)
training_images_x.shape

(27455, 784)

In [4]:
testing_images_x = testing_images.drop('label', axis=1)
print(testing_images_x.shape)

(7172, 784)


In [5]:
training_images_x = tf.reshape(training_images_x,[27455,28,28,1])
testing_images_x = tf.reshape(testing_images_x,[7172,28,28,1])

In [6]:
training_images_x.shape

TensorShape([27455, 28, 28, 1])

In [7]:
testing_images_x.shape

TensorShape([7172, 28, 28, 1])

In [8]:
tf.print(training_images_x)

[[[[107]
   [118]
   [127]
   ...
   [170]
   [170]
   [169]]

  [[111]
   [121]
   [129]
   ...
   [171]
   [171]
   [170]]

  [[113]
   [123]
   [131]
   ...
   [171]
   [171]
   [171]]

  ...

  [[142]
   [150]
   [159]
   ...
   [202]
   [201]
   [200]]

  [[142]
   [151]
   [160]
   ...
   [204]
   [203]
   [202]]

  [[142]
   [151]
   [160]
   ...
   [204]
   [203]
   [202]]]


 [[[155]
   [157]
   [156]
   ...
   [138]
   [92]
   [108]]

  [[158]
   [159]
   [159]
   ...
   [142]
   [116]
   [143]]

  [[161]
   [161]
   [161]
   ...
   [147]
   [125]
   [140]]

  ...

  [[162]
   [159]
   [145]
   ...
   [91]
   [101]
   [94]]

  [[153]
   [139]
   [115]
   ...
   [97]
   [95]
   [120]]

  [[135]
   [116]
   [95]
   ...
   [103]
   [135]
   [149]]]


 [[[187]
   [188]
   [188]
   ...
   [66]
   [77]
   [83]]

  [[188]
   [189]
   [189]
   ...
   [73]
   [73]
   [71]]

  [[190]
   [190]
   [190]
   ...
   [74]
   [68]
   [61]]

  ...

  [[212]
   [198]
   [175]
   ...
   [195]
  

In [9]:
tf.print(testing_images_x)

[[[[149]
   [149]
   [150]
   ...
   [150]
   [150]
   [149]]

  [[150]
   [150]
   [150]
   ...
   [151]
   [150]
   [151]]

  [[150]
   [151]
   [151]
   ...
   [151]
   [151]
   [152]]

  ...

  [[69]
   [69]
   [77]
   ...
   [116]
   [113]
   [118]]

  [[74]
   [75]
   [76]
   ...
   [110]
   [116]
   [113]]

  [[75]
   [74]
   [74]
   ...
   [112]
   [120]
   [107]]]


 [[[126]
   [128]
   [131]
   ...
   [133]
   [134]
   [132]]

  [[129]
   [132]
   [134]
   ...
   [136]
   [136]
   [134]]

  [[133]
   [135]
   [138]
   ...
   [140]
   [139]
   [138]]

  ...

  [[173]
   [174]
   [177]
   ...
   [184]
   [182]
   [181]]

  [[172]
   [174]
   [177]
   ...
   [184]
   [182]
   [181]]

  [[172]
   [174]
   [177]
   ...
   [184]
   [182]
   [180]]]


 [[[85]
   [88]
   [92]
   ...
   [182]
   [181]
   [178]]

  [[86]
   [88]
   [93]
   ...
   [183]
   [181]
   [179]]

  [[86]
   [89]
   [93]
   ...
   [185]
   [183]
   [181]]

  ...

  [[91]
   [94]
   [97]
   ...
   [224]
   [222]

In [10]:
training_images_y = training_images['label']
testing_images_y = testing_images['label']
training_images_y.shape

(27455,)

In [11]:
# To prevent dimensions of the form (m,)
# instead we want of the form (m,n)

training_images_y.to_numpy()
training_images_y = pd.DataFrame(training_images_y)
print(training_images_y.shape)

(27455, 1)


In [12]:
testing_images_y.to_numpy()
testing_images_y = pd.DataFrame(testing_images_y)
print(testing_images_y.shape)

(7172, 1)


In [13]:
from tensorflow import keras
from sklearn.preprocessing import LabelBinarizer

In [14]:
# One vs all classification
label_binrizer = LabelBinarizer()
training_images_y = label_binrizer.fit_transform(training_images_y)

In [15]:
training_images_x = training_images_x/255
testing_images_x = testing_images_x/255

model = tf.keras.models.Sequential([ 
    tf.keras.layers.Conv2D(6,(5,5),activation=tf.nn.relu, input_shape = (28,28,1)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(16,(5,5),activation=tf.nn.relu),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation = tf.nn.relu),
    tf.keras.layers.Dense(84, activation = tf.nn.relu),
    tf.keras.layers.Dense(24, activation = tf.nn.softmax), # 24 units because there are 24 classes in the dataset
])

model.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

history = model.fit(
    training_images_x, training_images_y, epochs = 5,
)

Epoch 1/5
858/858 [==============================] - 3s 3ms/step - loss: 1.0921 - accuracy: 0.6600
Epoch 2/5
858/858 [==============================] - 3s 3ms/step - loss: 0.1151 - accuracy: 0.9686
Epoch 3/5
858/858 [==============================] - 2s 3ms/step - loss: 0.0237 - accuracy: 0.9954
Epoch 4/5
858/858 [==============================] - 3s 3ms/step - loss: 0.0415 - accuracy: 0.9877
Epoch 5/5
858/858 [==============================] - 3s 3ms/step - loss: 8.9469e-04 - accuracy: 1.0000


In [16]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 24, 6)         156       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 8, 16)          2416      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 256)               0         
_________________________________________________________________
dense (Dense)                (None, 256)               65792     
_________________________________________________________________
dense_1 (Dense)              (None, 84)                2

In [17]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(testing_images_x)

In [18]:
testing_images_y = label_binrizer.fit_transform(testing_images_y)
accuracy_score(testing_images_y, y_pred.round())

0.8898494143892917